packages:
  - packages/core
  - packages/crypto
  - packages/mdoc/*
  - packages/jose
  - packages/jarm
catalog:
  '@types/node': ^20.14.11
  eslint: ^9.9.0
  prettier: ^3.3.3
  tsx: ^4.11.2
  typescript: ^5.5.4
  valibot: 0.37.0
  msw: ^2.3.5
  jose: ^5.6.3
  '@ausweis/typescript': ^0.2.34
  '@ausweis/eslint': ^0.2.34
  '@ausweis/prettier': ^0.2.34
